#!/bin/bash

options="poweroff\nreboot\nsuspend\nlogout"
cmd=$(echo -e "$options" | rofi -dmenu -width 10 -lines 5 -p quit:)
case $cmd in
logout)
    pkill xmonad
    ;;
*)
    systemctl $cmd
    ;;
esac

