#!/usr/bin/env bash

if [ ! -z "$@" ]; then
    dir=${@/#doc\:/$HOME\/Documents}
    coproc ( $TERMINAL --directory "$dir" > /dev/null 2>&1 )
    exec 1>&-
    exit
fi

while read -r line; do
    echo "$line"
done <<< `find ~/Documents -maxdepth 5 -type d -printf '%d doc:/%P\n' | sort -n | awk '{ print $2 }'`
