#!/usr/bin/env bash

if [ ! -z "$@" ]; then
    case "$@" in
        logout)
            coproc ( riverctl exit >/dev/null 2>&1 )
            exec 1>&-
            exit
            ;;
        *)
            coproc ( systemctl "$@" >/dev/null 2>&1 )
            exec 1>&-
            exit
            ;;
    esac
fi

echo "hibernate"
echo "suspend-then-hibernate"
echo "suspend"
echo "logout"
echo "reboot"
echo "poweroff"
