#!/bin/sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
import-gsettings
swaybg --image ~/Pictures/yanfei-hayaroB-2x.png &
waybar &
udiskie --appindicator &
nm-applet --indicator &
blueman-applet &
copyq &
kanshi &
