#!/bin/sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xdg-desktop-portal-wlr &
import-gsettings
swaybg --image ~/Pictures/yanfei-hayaroB-2x.png &
waybar &
udiskie --appindicator &
nm-applet --indicator &
blueman-applet &
copyq &
mako &
kanshi &
